version: '3'
services:
  backend-db:
    container_name: backend-db
    command: mysqld --character-set-server=utf8 --ssl=0 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    image: mysql:8.0.0
    environment:
      - MYSQL_ROOT_PASSWORD=fgl09044
      - MYSQL_USER=backend
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=backend
    ports:
      - "8013:3306"
    expose:
      - 8013
    volumes:
      - /var/docker/volumes/backend-db:/var/lib/mysql